# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='nome de galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='breno', verbose_name='Imagem')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ronaldosite.Galeria', verbose_name='galeria')),
            ],
        ),
    ]
