# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldosite', '0002_auto_20170228_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='media/breno', verbose_name='Imagem'),
        ),
    ]
