# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldosite', '0003_auto_20170228_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='breno', verbose_name='Imagem'),
        ),
    ]
